### ISSUE TITLE
Going through the book doesn't work

### ISSUE THREAD

**Issue by calberts** [OpenStackCookbook/OpenStackCookbook#13]
Hoi

I have your book and i’m going trough the commands it looks like  its not working
i am stuck on creating mysql database i think that there are some syntax issue

I read i from ibooks and i highlight the commands after that i can put them in the command line

The ones markt with \* are problem

although by installing the my sql the window to give the root password was also popping up because the \ in green where to much

did you test als the scripting and is there on the GIT a list of al commands  in txt file which i can use to walkthrough

MYSQL_ROOT_PASS=openstack

MYSQL_HOST=172.16.0.200
# To enable non-interactive installations of MySQL, set the following

echo "mysql-server-5.5 mysql-server/root_password password \ $MYSQL_ROOT_PASS" | sudo debconf-set-selections

echo "mysql-server-5.5 mysql-server/root_password_again password \ $MYSQL_ROOT_PASS" | sudo debconf-set-selections

echo "mysql-server-5.5 mysql-server/root_password seen true"  | sudo debconf-set-selections

echo "mysql-server-5.5 mysql-server/root_password_again seen true" \  | sudo debconf-set-selections

export DEBIAN_FRONTEND=noninteractive

sudo apt-get update

sudo apt-get -q -y install mysql-server                                                    #root password is openstack  zie eerste statemenet
- sudo sed -i "s/^bind-address.*/bind-address = ${MYSQL_HOST}/g" \ /etc/mysql/my.cnf       probleem bestond wel

sudo service mysql restart
- mysqladmin -uroot password ${MYSQL_ROOT_PASS}

mysql -u root --password=${MYSQL_ROOT_PASS} -h localhost \ -e "GRANT ALL ON _._ to root@\"localhost\" IDENTIFIED BY \"${MYSQL_ROOT_PASS}\" WITH GRANT OPTION;"

mysql -u root --password=${MYSQL_ROOT_PASS} -h localhost \ -e "GRANT ALL ON _._ to root@\"${MYSQL_HOST}\" IDENTIFIED BY \"${MYSQL_ROOT_PASS}\" WITH GRANT OPTION;"

mysql -u root --password=${MYSQL_ROOT_PASS} -h localhost \ -e "GRANT ALL ON _._ to root@\"%\" IDENTIFIED BY \"${MYSQL_ROOT_PASS}\" WITH GRANT OPTION;"

mysqladmin -uroot -p${MYSQL_ROOT_PASS} flush-privileges

How to get this right?

Chris Alberts

**Comment by kenkensh** [comment]
@calberts @udemy1  did you fix the mysql installation issue around  finally, I just follow the openstack clouding computing cookbook second editon handbook  to deploy my openstack sandbox but  encounter the issue as well
vagrant@controller:~$ mysqladmin -uroot password ${MYSQL_ROOT_PASS}
 mysqladmin: connect to server at 'localhost' failed
 error: 'Access denied for user 'root'@'localhost' (using password: NO)'
no clue to fix , because I am new to mysql and openstack. google it but no solution 

@uksysadmin  May I have the "correct and verfied" script code for 2nd edtion can be used directly. or just you guys don't want us to use old version and push to 3rd edition now. Thanks.
